// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdMEzaEuvdi9LNhUGaVIuexbD8BrW_azE',
    appId: '1:764816137701:web:cbe9d08f33a6d9c6fae30c',
    messagingSenderId: '764816137701',
    projectId: 'dermaai-a8bda',
    authDomain: 'dermaai-a8bda.firebaseapp.com',
    storageBucket: 'dermaai-a8bda.firebasestorage.app',
    measurementId: 'G-E3HQ0MYL1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5v36dFdvUePy3HovhfJihSTfIR_qsN2g',
    appId: '1:764816137701:android:c1b9fd40f8afd72bfae30c',
    messagingSenderId: '764816137701',
    projectId: 'dermaai-a8bda',
    storageBucket: 'dermaai-a8bda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXUEi3rE3z2HY-3Y9r5YNq7z6bBom7KY',
    appId: '1:764816137701:ios:ae71ca4e0363b3a9fae30c',
    messagingSenderId: '764816137701',
    projectId: 'dermaai-a8bda',
    storageBucket: 'dermaai-a8bda.firebasestorage.app',
    iosBundleId: 'com.example.dermaai',
  );
}
